# Generated by Django 5.2 on 2025-04-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelog',
            name='authorised',
            field=models.BooleanField(default=False),
        ),
    ]
